url: 'http://ianks.com'
title: 'ianks'
port: 3000
gems:
  - jemoji
exclude:
  - 'README.md'
  - 'CHANGELOG.md'
  - 'CNAME'
  - 'Gemfile'
  - 'Gemfile.lock'
permalink: :title
defaults:
  -
    scope:
      path: ''
      type: 'pages'
    values:
      layout: 'default'
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
sass:
  style: compressed
markdown: redcarpet
